# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_processing.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_image_processing(object):
    def setupUi(self, image_processing):
        image_processing.setObjectName("image_processing")
        image_processing.resize(1122, 688)
        image_processing.setMinimumSize(QtCore.QSize(720, 480))
        image_processing.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(image_processing)
        self.centralwidget.setStyleSheet("#centralwidget { \n"
"    background-color: qlineargradient(spread:pad, x1:0.084, y1:0.329545, x2:0.901, y2:0.551136, stop:0 rgba(221, 255, 199, 255), stop:0.232451 rgba(187, 255, 184, 255), stop:0.680092 rgba(221, 255, 164, 255), stop:1 rgba(145, 255, 161, 255));\n"
"}\n"
"#delete_watermark_button, #open_watermark_button, #update_button, #select_filegroup, #save_filegroup, #open_preview, #save_preview { \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(114, 201, 113, 137), stop:0.264151 rgba(116, 234, 105, 211), stop:0.496115 rgba(188, 224, 133, 124), stop:0.778024 rgba(163, 228, 112, 220), stop:1 rgba(214, 255, 152, 182));}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setStyleSheet("font: 10pt \"Garamond\";")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_groupbox = QtWidgets.QGroupBox(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.left_groupbox.sizePolicy().hasHeightForWidth())
        self.left_groupbox.setSizePolicy(sizePolicy)
        self.left_groupbox.setObjectName("left_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.picture_label = QtWidgets.QLabel(self.left_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.picture_label.sizePolicy().hasHeightForWidth())
        self.picture_label.setSizePolicy(sizePolicy)
        self.picture_label.setObjectName("picture_label")
        self.verticalLayout.addWidget(self.picture_label)
        self.horizontalLayout.addWidget(self.left_groupbox)
        self.right_groupbox = QtWidgets.QGroupBox(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.right_groupbox.sizePolicy().hasHeightForWidth())
        self.right_groupbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.right_groupbox.setFont(font)
        self.right_groupbox.setCheckable(False)
        self.right_groupbox.setObjectName("right_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_preview = QtWidgets.QPushButton(self.right_groupbox)
        self.open_preview.setObjectName("open_preview")
        self.verticalLayout_2.addWidget(self.open_preview)
        self.save_preview = QtWidgets.QPushButton(self.right_groupbox)
        self.save_preview.setObjectName("save_preview")
        self.verticalLayout_2.addWidget(self.save_preview)
        self.groupBox = QtWidgets.QGroupBox(self.right_groupbox)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.open_watermark_button = QtWidgets.QPushButton(self.groupBox)
        self.open_watermark_button.setObjectName("open_watermark_button")
        self.verticalLayout_3.addWidget(self.open_watermark_button)
        self.watermark_path_label = QtWidgets.QLabel(self.groupBox)
        self.watermark_path_label.setText("")
        self.watermark_path_label.setObjectName("watermark_path_label")
        self.verticalLayout_3.addWidget(self.watermark_path_label)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.watermark_position_x = QtWidgets.QSpinBox(self.groupBox)
        self.watermark_position_x.setMaximum(10000)
        self.watermark_position_x.setObjectName("watermark_position_x")
        self.horizontalLayout_3.addWidget(self.watermark_position_x)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.watermark_position_y = QtWidgets.QSpinBox(self.groupBox)
        self.watermark_position_y.setMaximum(10000)
        self.watermark_position_y.setObjectName("watermark_position_y")
        self.horizontalLayout_3.addWidget(self.watermark_position_y)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.watermark_scale_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.watermark_scale_spinbox.setMinimum(1)
        self.watermark_scale_spinbox.setMaximum(100000)
        self.watermark_scale_spinbox.setProperty("value", 100)
        self.watermark_scale_spinbox.setObjectName("watermark_scale_spinbox")
        self.horizontalLayout_4.addWidget(self.watermark_scale_spinbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.delete_watermark_button = QtWidgets.QPushButton(self.groupBox)
        self.delete_watermark_button.setObjectName("delete_watermark_button")
        self.verticalLayout_3.addWidget(self.delete_watermark_button)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.right_groupbox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.orig_size = QtWidgets.QLabel(self.groupBox_2)
        self.orig_size.setObjectName("orig_size")
        self.horizontalLayout_9.addWidget(self.orig_size)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.curr_size = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curr_size.setFont(font)
        self.curr_size.setObjectName("curr_size")
        self.horizontalLayout_9.addWidget(self.curr_size)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.main_img_scale_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_img_scale_spinbox.sizePolicy().hasHeightForWidth())
        self.main_img_scale_spinbox.setSizePolicy(sizePolicy)
        self.main_img_scale_spinbox.setMinimum(1)
        self.main_img_scale_spinbox.setMaximum(10000)
        self.main_img_scale_spinbox.setProperty("value", 100)
        self.main_img_scale_spinbox.setObjectName("main_img_scale_spinbox")
        self.horizontalLayout_8.addWidget(self.main_img_scale_spinbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.right_groupbox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.select_filegroup = QtWidgets.QPushButton(self.groupBox_3)
        self.select_filegroup.setObjectName("select_filegroup")
        self.horizontalLayout_11.addWidget(self.select_filegroup)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.input_filegroup_path = QtWidgets.QLabel(self.groupBox_3)
        self.input_filegroup_path.setText("")
        self.input_filegroup_path.setObjectName("input_filegroup_path")
        self.horizontalLayout_11.addWidget(self.input_filegroup_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.save_filegroup = QtWidgets.QPushButton(self.groupBox_3)
        self.save_filegroup.setObjectName("save_filegroup")
        self.verticalLayout_5.addWidget(self.save_filegroup)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.update_button = QtWidgets.QPushButton(self.right_groupbox)
        self.update_button.setObjectName("update_button")
        self.verticalLayout_2.addWidget(self.update_button)
        self.manual_update_mode_checkBox = QtWidgets.QCheckBox(self.right_groupbox)
        self.manual_update_mode_checkBox.setObjectName("manual_update_mode_checkBox")
        self.verticalLayout_2.addWidget(self.manual_update_mode_checkBox)
        self.horizontalLayout.addWidget(self.right_groupbox)
        self.horizontalLayout_2.addWidget(self.main_widget)
        image_processing.setCentralWidget(self.centralwidget)
        self.open_single_image_action = QtWidgets.QAction(image_processing)
        self.open_single_image_action.setObjectName("open_single_image_action")
        self.save_as_action = QtWidgets.QAction(image_processing)
        self.save_as_action.setObjectName("save_as_action")

        self.retranslateUi(image_processing)
        QtCore.QMetaObject.connectSlotsByName(image_processing)

    def retranslateUi(self, image_processing):
        _translate = QtCore.QCoreApplication.translate
        image_processing.setWindowTitle(_translate("image_processing", "Наложение водяного знака"))
        self.left_groupbox.setTitle(_translate("image_processing", "Предпросмотр"))
        self.picture_label.setText(_translate("image_processing", "picture preview"))
        self.right_groupbox.setTitle(_translate("image_processing", "Инструменты"))
        self.open_preview.setText(_translate("image_processing", "Открыть картинку для предпросмотра"))
        self.save_preview.setText(_translate("image_processing", "Сохранить картинку с предпросмотра"))
        self.groupBox.setTitle(_translate("image_processing", "Картинка для наложения"))
        self.open_watermark_button.setText(_translate("image_processing", "Открыть картинку для наложения..."))
        self.label.setText(_translate("image_processing", "Расположение (px):"))
        self.label_2.setText(_translate("image_processing", "x:"))
        self.label_3.setText(_translate("image_processing", "y:"))
        self.label_4.setText(_translate("image_processing", "Размер накладываемой картинки (% от оригинального):"))
        self.delete_watermark_button.setText(_translate("image_processing", "Удалить накладываемую картинку"))
        self.groupBox_2.setTitle(_translate("image_processing", "Изменить фоновое изображение"))
        self.label_6.setText(_translate("image_processing", "Оригинальный размер:"))
        self.orig_size.setText(_translate("image_processing", "(w, h)"))
        self.label_7.setText(_translate("image_processing", "Текущий размер:"))
        self.curr_size.setText(_translate("image_processing", "(w,h)"))
        self.label_5.setText(_translate("image_processing", "Размер (% от оригинального)"))
        self.groupBox_3.setTitle(_translate("image_processing", "Применить к группе фотографий"))
        self.select_filegroup.setText(_translate("image_processing", "Выбрать папку с фотографиями"))
        self.label_8.setText(_translate("image_processing", "Выбрано:"))
        self.save_filegroup.setText(_translate("image_processing", "Сохранить в..."))
        self.update_button.setText(_translate("image_processing", "Обновить предпросмотр"))
        self.manual_update_mode_checkBox.setToolTip(_translate("image_processing", "Отметьте этот чекбокс, чтобы отключить автоматическое обновление картинки предпросмотра. Рекомендуется, если ПК работает медленно. Получить обновленный предпросмотр можно нажатием кнопки \"Обновить предпросмотр\""))
        self.manual_update_mode_checkBox.setText(_translate("image_processing", "Режим ручного обновления (для слабой техники)"))
        self.open_single_image_action.setText(_translate("image_processing", "Открыть изображение..."))
        self.save_as_action.setText(_translate("image_processing", "Сохранить как..."))
