# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setMinimumSize(QtCore.QSize(480, 640))
        MainWindow.setMaximumSize(QtCore.QSize(480, 640))
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget { background-color: qlineargradient(spread:pad, x1:0.084, y1:0.329545, x2:0.901, y2:0.551136, stop:0 rgba(221, 255, 199, 255), stop:0.232451 rgba(187, 255, 184, 255), stop:0.680092 rgba(221, 255, 164, 255), stop:1 rgba(145, 255, 161, 255)); }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(230, 0, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 26pt \"Gabriola\";\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(52, 200, 25, 197), stop:0.375415 rgba(26, 161, 0, 146), stop:0.448589 rgba(0, 214, 7, 255), stop:0.477581 rgba(62, 189, 52, 130), stop:0.518272 rgba(86, 222, 61, 183), stop:0.55 rgba(2, 255, 0, 255), stop:0.57754 rgba(73, 203, 0, 174), stop:0.625415 rgba(35, 211, 0, 188), stop:1 rgba(255, 255, 0, 69));")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(-10, 0, 241, 91))
        self.label.setStyleSheet("background-image: url(zelenkvit.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("#prepare_order_btn, #send_bill_btn, #photo_processing_btn {\n"
"    background-color: qconicalgradient(cx:0, cy:0, angle:113.4, stop:0 rgba(33, 127, 15, 255), stop:0.306908 rgba(18, 116, 0, 255), stop:0.386183 rgba(0, 171, 5, 255), stop:0.473386 rgba(47, 144, 39, 255), stop:0.518272 rgba(62, 162, 44, 255), stop:0.549264 rgba(1, 177, 0, 255), stop:0.640997 rgba(49, 137, 0, 255), stop:0.698754 rgba(27, 164, 0, 255), stop:1 rgba(23, 129, 0, 255));\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.photo_processing_btn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.photo_processing_btn.sizePolicy().hasHeightForWidth())
        self.photo_processing_btn.setSizePolicy(sizePolicy)
        self.photo_processing_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.photo_processing_btn.setFont(font)
        self.photo_processing_btn.setObjectName("photo_processing_btn")
        self.gridLayout.addWidget(self.photo_processing_btn, 5, 1, 1, 1)
        self.prepare_order_btn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prepare_order_btn.sizePolicy().hasHeightForWidth())
        self.prepare_order_btn.setSizePolicy(sizePolicy)
        self.prepare_order_btn.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.prepare_order_btn.setFont(font)
        self.prepare_order_btn.setObjectName("prepare_order_btn")
        self.gridLayout.addWidget(self.prepare_order_btn, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.send_bill_btn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_bill_btn.sizePolicy().hasHeightForWidth())
        self.send_bill_btn.setSizePolicy(sizePolicy)
        self.send_bill_btn.setMinimumSize(QtCore.QSize(249, 80))
        self.send_bill_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(12)
        self.send_bill_btn.setFont(font)
        self.send_bill_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.send_bill_btn.setAutoFillBackground(False)
        self.send_bill_btn.setObjectName("send_bill_btn")
        self.gridLayout.addWidget(self.send_bill_btn, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Зеленквіт managment tools"))
        self.label_2.setText(_translate("MainWindow", "managment tools"))
        self.photo_processing_btn.setText(_translate("MainWindow", "Обработать фотографии"))
        self.prepare_order_btn.setText(_translate("MainWindow", "Сформировать заказ"))
        self.send_bill_btn.setText(_translate("MainWindow", "Выставить счет для оплаты"))
